# Generated by Django 3.0.5 on 2020-08-21 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200821_2216'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='no',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.OneToOneField(default=99, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(default='New Scheme', max_length=20, verbose_name='Type of application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='applied_on',
            field=models.DateField(auto_now=True, verbose_name='Date applied'),
        ),
        migrations.AddField(
            model_name='application',
            name='office',
            field=models.OneToOneField(default=99, on_delete=django.db.models.deletion.CASCADE, to='accounts.Office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='sanctioned_by',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, related_name='sanctioned_schemes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='scheme',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='applications.Scheme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Granted', 'Granted'), ('Rejected', 'Rejected')], default='Pending', max_length=8, verbose_name='Application Status'),
        ),
    ]
