# Generated by Django 3.0.5 on 2020-08-22 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200822_0728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0003_auto_20200822_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Office'),
        ),
    ]
