# Generated by Django 3.0.5 on 2020-08-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20200822_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='time_period',
            field=models.IntegerField(default=30, help_text='Number of days to complete processing', verbose_name='Time Period'),
            preserve_default=False,
        ),
    ]
