# Generated by Django 3.0.5 on 2020-08-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_scheme_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='attachments',
            field=models.FileField(blank=True, upload_to='schemes/', verbose_name='Supporting Documents'),
        ),
        migrations.CreateModel(
            name='SupportingDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, upload_to='supporting_docs/', verbose_name='Supporting Documents')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application')),
            ],
        ),
    ]
