# Generated by Django 3.0.5 on 2020-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20200822_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdoc',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='supporting_docs/', verbose_name='Supporting Documents'),
        ),
    ]
