# Generated by Django 3.0.5 on 2020-08-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20200822_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdoc',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportingdoc', to='applications.Application'),
        ),
    ]
