# Generated by Django 3.0.5 on 2020-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20200822_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
    ]
