# Generated by Django 3.0.5 on 2020-08-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='redirected_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
    ]
