# Generated by Django 3.0.5 on 2020-08-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_redirected_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificate/', verbose_name='Certificate')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='applications.Application')),
            ],
        ),
    ]
