# Generated by Django 3.0.5 on 2020-08-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20200823_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='year_created',
        ),
        migrations.AddField(
            model_name='scheme',
            name='validity',
            field=models.IntegerField(default=365, help_text='Days of validity', verbose_name='Days'),
            preserve_default=False,
        ),
    ]
