# Generated by Django 3.0.5 on 2020-08-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20200823_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
    ]
