# Generated by Django 3.0.5 on 2020-08-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email_id', models.EmailField(help_text='Please enter applicants Email ID.', max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Email ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_official', models.BooleanField(default=False, verbose_name='official status')),
                ('is_applicant', models.BooleanField(default=False, verbose_name='applicant status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
