# Generated by Django 3.0.5 on 2020-08-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200822_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Office'),
        ),
    ]
