# Generated by Django 3.0.5 on 2020-08-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200821_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_no',
            field=models.IntegerField(default=1, verbose_name='Aadhar No'),
            preserve_default=False,
        ),
    ]
