# Generated by Django 3.0.5 on 2020-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=50, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
