# Generated by Django 3.0.5 on 2020-08-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.CharField(max_length=30, verbose_name='Office Type')),
                ('district', models.CharField(choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasargod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malappuram'), ('PL', 'Palakkad'), ('PT', 'Pathanamthitta'), ('TV', 'Thiruvananthapuram'), ('TS', 'Thrissur'), ('WA', 'Wayanad')], max_length=2, verbose_name='District')),
                ('location', models.CharField(max_length=30, verbose_name='Location of the office')),
            ],
        ),
        migrations.AddField(
            model_name='official',
            name='position',
            field=models.CharField(default='clerk', max_length=50, verbose_name='Position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='official',
            name='office',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.Office'),
            preserve_default=False,
        ),
    ]
